spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fabrication?useSSL=false&serverTimezone=UTC
    username: root         # ou ton user XAMPP
    password: ""           # ton mot de passe
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
